DROP TABLE FFC_SERVICE;
DROP TABLE CUSTOMER_FLIGHT_RECORDS;
DROP TABLE CHECK_IN;
DROP TABLE SEAT_RESERVATION;
DROP TABLE CUSTOMER;
DROP TABLE LEG_INSTANCE;
DROP TABLE FLIGHT_LEG;
DROP TABLE FARE;
DROP TABLE FLIGHT;
DROP TABLE AIRPLANE;
DROP TABLE CAN_LAND;
DROP TABLE AIRPLANE_TYPE;
DROP TABLE AIRLINE_COMPANY;
DROP TABLE AIRPLANE_COMPANY;
DROP TABLE AIRPORT;
 
-- ---------------------------------------------------

DROP TRIGGER create_customer_flight_records;
DROP TRIGGER create_ffc;
DROP TRIGGER updating_the_ffc_mileage;
DROP TRIGGER flight_count_update;
DROP TRIGGER available_seat_update;

DROP VIEW Number_Of_Airplane_Types_That_Can_Land_To_Airports;
DROP VIEW Extended_FFC;
DROP VIEW Flight_with_price;
DROP VIEW Flight_Instance;
DROP VIEW Customer_flight_records_with_fare_amounts;

SHOW tables;